baseURL = "https://2019.djangocon.eu/"
languageCode = "en-us"
title = "DjangoCon Europe 2019"
theme = "dceu2019"
author = "Django Denmark"

[params]

    description = "DjangoCon Europe, In Copenhagen April 10-12th 2019"
    twittercardimage="twitter_square.png"
    headerimage = "logo-white.svg"

[[menu.main]]
    name = "Call for Participation"
    url  = "/cfp"
[[menu.main]]
    name = "Code of Conduct"
    url  = "/conduct"
[[menu.main]]
    name = "Sponsors"
    url  = "/sponsors"
[[menu.main]]
    name = "Contact"
    url  = "/contact"
