baseURL = "https://2019.djangocon.eu/"
languageCode = "en-us"
title = "DjangoCon Europe 2019"
theme = "dceu2019"
author = "Django Denmark"

[params]

    headerimage = "logo_small.png"

[[menu.main]]
    name = "CfP"
    url  = "/cfp"
[[menu.main]]
    name = "Sponsors"
    url  = "/sponsors"
[[menu.main]]
    name = "Contact"
    url  = "/contact"
